version: "3.1"

volumes:
    nginx_data:
        driver: local

services:
    ro-frontend:
        image: 'ro-frontend:latest'
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - 'nginx_data:/var/log/nginx'
            - 'nginx_data:/etc/nginx'
        ports:
            - '30080:30080'
        environment:
            - ALLOW_ANONYMOUS_LOGIN=true
